# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChildWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from img import img_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_child_windows(object):
    def setupUi_(self, child_windows):
        child_windows.setObjectName("child_windows")
        child_windows.resize(1222, 853)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ChildWindows/ChildWindow_Edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        child_windows.setWindowIcon(icon)
        self.search_name = QtWidgets.QListView(child_windows)
        self.search_name.setGeometry(QtCore.QRect(5, 1, 451, 841))
        self.search_name.setObjectName("search_name")
        self.search_file_ = QtWidgets.QListView(child_windows)
        self.search_file_.setGeometry(QtCore.QRect(450, 1, 461, 841))
        self.search_file_.setObjectName("search_file")
        self.search_size = QtWidgets.QListView(child_windows)
        self.search_size.setGeometry(QtCore.QRect(906, 1, 311, 841))
        self.search_size.setObjectName("search_size")

        self.retranslateUi(child_windows)
        QtCore.QMetaObject.connectSlotsByName(child_windows)

    def retranslateUi(self, child_windows):
        _translate = QtCore.QCoreApplication.translate
        child_windows.setWindowTitle(_translate("child_windows", "搜索目录"))

